### ISSUE TITLE
createAnimation中的参数不起作用

### ISSUE THREAD

**Issue by MarshallYang** [raxjs/miniapp#180]
设置 `createAnimation` 中的参数例如 `duration: 100`，实际情况不起作用。

具体代码：
![](https://z3.ax1x.com/2021/07/15/WunwcV.png)

实际 `console.log` 的输出
![](https://z3.ax1x.com/2021/07/15/Wund10.png)

期望：
能正确赋值

**Comment by peakchen90** [comment]
@MarshallYang 你好，请问是在哪个容器上出现的问题，`console.log` 打印的是 `data.export()` 的值吗

**Comment by MarshallYang** [comment]
> @MarshallYang 你好，请问是在哪个容器上出现的问题，`console.log` 打印的是 `data.export()` 的值吗

支付宝和微信都有。打印内容是传入的动画对象 `anim`  

`<View animation={anim} />`

**Comment by peakchen90** [comment]
@MarshallYang 已经找到问题了，近期会修复掉

**Comment by DOBEEE** [comment]
@uni/animation@1.0.2 已发布
