### ISSUE TITLE
期待一个简版 使用vite或rollup 打包 rax-core 的 纯运行时的 hello world demo

### ISSUE THREAD

**Issue by yuchonghua** [raxjs/miniapp#249]
背景：希望自己实现一个使用 [vite](https://cn.vitejs.dev/)或[rollup](https://rollupjs.org/guide/zh/) 打包 [rax-core](https://github.com/alibaba/rax) 纯运行时的 hello world 的简版demo

----

1、期待有一个 使用[vite](https://cn.vitejs.dev/)或[rollup](https://rollupjs.org/guide/zh/) 打包 [rax-core](https://github.com/alibaba/rax) 纯运行时的 hello world demo
2、如果 1 没有现成的，期待有个大致的实现思路，侧重了解运行时的实现方案

**Comment by ChrisCindy** [comment]
暂无该方面的计划，目前我们的思路是使用 webpack 5 配合 swc 等加速构建

**Comment by yuchonghua** [comment]
> 暂无该方面的计划，目前我们的思路是使用 webpack 5 配合 swc 等加速构建

蛋蛋的忧伤
