### ISSUE TITLE
双引擎融合方案实现

### ISSUE THREAD

**Issue by ChrisCindy** [raxjs/miniapp#32]
GOAL: 支持在单一运行时项目中灵活配置使用编译时组件
USAGE: 用户在 src/miniapp-compiled 文件夹中放置且被使用到的组件全部使用编译时引擎编译
TODO:  
- [x] babel 插件扫描，将 miniapp-compiled 文件夹内的组件识别为原生自定义组件
- [x] 接入编译时组件工程，编译 miniapp-compiled 文件夹内使用到的组件
- [x] 工程体验优化，自动进入产物文件夹进行 npm install
- [x] 编译时组件引入方式可以按照正常书写习惯，无需按照 usingComponents 的方式书写完整路径
- [x] babel 插件在每次文件变化编译时均重新扫描输出 props 和 events
- [x] miniapp-render 文件处理逻辑优化，支持直接安装依赖以覆盖默认配置

**Comment by imsobear** [comment]
没看懂用户是怎么用的

**Comment by ChrisCindy** [comment]
> 没看懂用户是怎么用的

我补充一下

**Comment by ChrisCindy** [comment]
https://github.com/alibaba/ice/pull/3766
